# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-10 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckBoxItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='CheckboxName')),
            ],
        ),
        migrations.CreateModel(
            name='FormItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateField(default=django.utils.timezone.now, verbose_name='RegistrationDate')),
                ('checked', models.BooleanField(verbose_name='YesNo')),
                ('input_text', models.CharField(blank=True, max_length=255, verbose_name='InputText')),
                ('text_area', models.TextField(blank=True, verbose_name='TextArea')),
                ('checked_multiple', models.ManyToManyField(to='thinkami_reusable_app.CheckBoxItem', verbose_name='CheckdMultiple')),
            ],
        ),
        migrations.CreateModel(
            name='RadioItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='RadioName')),
            ],
        ),
        migrations.CreateModel(
            name='SelectItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='SelectName')),
            ],
        ),
        migrations.CreateModel(
            name='SelectMultipletem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='SelectName')),
            ],
        ),
        migrations.AddField(
            model_name='formitem',
            name='pushed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='thinkami_reusable_app.RadioItem', verbose_name='Pushed'),
        ),
        migrations.AddField(
            model_name='formitem',
            name='selected',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='thinkami_reusable_app.SelectItem', verbose_name='Selected'),
        ),
        migrations.AddField(
            model_name='formitem',
            name='selected_multiple',
            field=models.ManyToManyField(to='thinkami_reusable_app.SelectMultipletem', verbose_name='SelectedMultiple'),
        ),
    ]
